name: Sehati
description: 
version: 1.1.2
homepage: https://github.com/username/iqmal_flutter_library
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.18.1
  provider: ^6.1.5
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  fl_chart: ^0.63.0
  flutter_local_notifications: 17.2.4
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  timezone: ^0.9.4
  permission_handler: ^11.3.0
  file_saver: ^0.2.2
  pdf: any
  printing: any  
  shimmer: ^3.0.0
  google_fonts: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Atau versi terbaru

flutter:
  uses-material-design: true  # Mengaktifkan Material Design di aplikasi Anda

  assets:
    # Daftar aset gambar dan lainnya jika diperlukan
    - assets/images/background.jpg
    - assets/images/default_user.png
    - assets/images/sehati_logo.png
    